package kali.application;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class AutoGenerated {

//	@Id 
	//@GeneratedValue(strategy=GenerationType.AUTO)
	//private int id;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int userId;
	
	//mySql Does not support sequence
	//@Id
	//@GeneratedValue(strategy=GenerationType.SEQUENCE)
	//private int key;

}
